# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protobufs import transactions_pb2 as protobufs_dot_transactions__pb2


class TransactionsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetList = channel.unary_unary(
                '/Transactions/GetList',
                request_serializer=protobufs_dot_transactions__pb2.SearchRequest.SerializeToString,
                response_deserializer=protobufs_dot_transactions__pb2.TransactionsList.FromString,
                )


class TransactionsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TransactionsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetList,
                    request_deserializer=protobufs_dot_transactions__pb2.SearchRequest.FromString,
                    response_serializer=protobufs_dot_transactions__pb2.TransactionsList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Transactions', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Transactions(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Transactions/GetList',
            protobufs_dot_transactions__pb2.SearchRequest.SerializeToString,
            protobufs_dot_transactions__pb2.TransactionsList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
