# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transactions.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'transactions.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12transactions.proto\x12\tprotobufs\"L\n\rSearchRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\x13\n\x0bpage_number\x18\x02 \x01(\x05\x12\x17\n\x0fresult_per_page\x18\x03 \x01(\x05\"?\n\x10TransactionsList\x12+\n\x0btransaction\x18\x01 \x03(\x0b\x32\x16.protobufs.Transaction\"\x9c\x02\n\x0bTransaction\x12\x13\n\x0b\x64\x61ta_source\x18\x01 \x01(\t\x12\x11\n\tclient_id\x18\x02 \x01(\t\x12\x0f\n\x07\x61\x63\x63ount\x18\x03 \x01(\t\x12\x16\n\x0etransaction_id\x18\x04 \x01(\t\x12\x15\n\rrelated_asset\x18\x05 \x01(\t\x12\x18\n\x10transaction_type\x18\x06 \x01(\t\x12\r\n\x05\x61sset\x18\x07 \x01(\t\x12\x11\n\ttimestamp\x18\x08 \x01(\t\x12\x10\n\x08order_id\x18\t \x01(\t\x12\x16\n\x0eorder_position\x18\n \x01(\t\x12\x17\n\x0frelated_account\x18\x0b \x01(\t\x12\x17\n\x0ftransaction_sum\x18\x0c \x01(\t\x12\r\n\x05split\x18\r \x01(\t2R\n\x0cTransactions\x12\x42\n\x07GetList\x12\x18.protobufs.SearchRequest\x1a\x1b.protobufs.TransactionsList\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transactions_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SEARCHREQUEST']._serialized_start=33
  _globals['_SEARCHREQUEST']._serialized_end=109
  _globals['_TRANSACTIONSLIST']._serialized_start=111
  _globals['_TRANSACTIONSLIST']._serialized_end=174
  _globals['_TRANSACTION']._serialized_start=177
  _globals['_TRANSACTION']._serialized_end=461
  _globals['_TRANSACTIONS']._serialized_start=463
  _globals['_TRANSACTIONS']._serialized_end=545
# @@protoc_insertion_point(module_scope)
